### PR TITLE
Bump copyright to 2018

### PR DESCRIPTION
**Pull request by LNJ2**

### CODE REVIEW

**Comment by IlyaBizyaev** [comment]
Looks really good 👍 

To make it just perfect, I would suggest to keep the original scheme and punctuation in this part in source files:
```
    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
```

**Comment by LNJ2** [comment]
I'm not sure, if this is good, because there are many different authors/contributors of one file. Only adding one (the first) author isn't really nice... Then theoretically the Kaidan.cpp and Kaidan.h were copyrighted to geobra, even if 99 % of the content was modified already by others. On the other side many projects do it this way, so it can't be so wrong...

**Comment by IlyaBizyaev** [comment]
No-no, not authors!
The authors lines is fine; it's just that we can conform to the scheme.

**Comment by LNJ2** [comment]
You mean, there is one empty line too much? or that there are `2017-2018` instead of `2017`? I don't see the difference to the scheme?

**Comment by IlyaBizyaev** [comment]
Currently:
```
/*
 *  Kaidan - A user-friendly XMPP client for every device!
 *
 *  Copyright (C) 2017-2018 Kaidan developers and contributors (see the LICENSE
 *  file for a full list of copyright authors)
 *
 *  Kaidan is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
```
Suggested:
```
/*
 *  Kaidan - A user-friendly XMPP client for every device
 *  Copyright (C) 2017-2018 Kaidan developers and contributors
 *  (see the LICENSE file for a full list of copyright authors)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
```
In doubt, use diff :)

**Comment by LNJ2** [comment]
I didn't removed the empty line between the description and the copyright line, because it made it much harder to read the copyright (there's also the see LICENSE line, now).

**Pull request merged**
