### PR TITLE
Render logos from source

### PR DESCRIPTION
**Pull request by JBBgameich**
While `git push`ing this ... I thought that there is maybe a better way to do this ...
If you know one, please share it with me :)

### CODE REVIEW

**Comment by IlyaBizyaev** [comment]
1) Uses wrong sizes
2) I used a different SVG for Android, can commit it if you wish
3) Uses some external tool named rendersvg
4) Does not optimize resulting images

**Comment by JBBgameich** [comment]
This external tool is called "function in a shell script" :)

**Comment by IlyaBizyaev** [comment]
@JBBgameich Ouch 😬

**Comment by JBBgameich** [comment]
> I used a different SVG for Android, can commit it if you wish

That would be nice, but don't hurry :)

> Does not optimize resulting images

fixed

> Uses wrong sizes

okay ... let me compare the sizes again

**Comment by LNJ2** [comment]
@IlyaBizyaev Are the sizes correct, now? If yes, I'd approve and merge it. :smiley:

**Comment by IlyaBizyaev** [comment]
I still haven't committed the SVG, so please wait with this one

**Comment by LNJ2** [comment]
Ah right, forgot about that ...

**Comment by LNJ2** [comment]
@JBBgameich Now you can update it to use the new icon :smiley:

**Comment by JBBgameich** [comment]
done

**Pull request merged**
