### PR TITLE
Use cmake + Ninja for building and installing (Ci and AppImage)

### PR DESCRIPTION
**Pull request by JBBgameich**

### CODE REVIEW

**Comment by LNJ2** [comment]
Why should we use ninja for building? I don't see any advantages and a new dependency?

**Comment by JBBgameich** [comment]
NInja is a little bit faster and quite small. And it's only for the Ci (I'm working on building the AppImages on there too) where a new dependency doesn't matter.

**Comment by LNJ2** [comment]
Do you need ninja for AppImages or what? I don't think the performance will differ much ...

**Comment by JBBgameich** [comment]
No, it's only philosophical :) Ninja is made to be used with a generator (Cmake in this case) while make was initially made to write Makefiles for it by hand.

```
Instead, Ninja is intended to be used with a separate program generating its input files. The generator program (like the ./configure found in autotools projects) can analyze system dependencies and make as many decisions as possible up front so that incremental builds stay fast. Going beyond autotools, even build-time decisions like "which compiler flags should I use?" or "should I build a debug or release-mode binary?" belong in the .ninja file generator.```

**Pull request merged**
