### PR TITLE
Add SQLite database for messages and roster caching

### PR DESCRIPTION
**Pull request by LNJ2**
Currently this is just a copy of the Chat tutorial, adapted to Kaidan.

### CODE REVIEW

**Comment by MRZA-MRZA** [comment]
Send button does nothing. So how can I test the code?

**Comment by MRZA-MRZA** [comment]
Send button does nothing. So how can I test the code?

**Comment by LNJ2** [comment]
Currently it doesn't work at all. It's WIP.

**Comment by MRZA-MRZA** [comment]
Sorry but "Make chat usable" sounds a bit misleading because chat is still not usable.

**Comment by LNJ2** [comment]
@MRZA-MRZA 
WIP mean work in progress -> This PR should not be merged and it still has to be worked on it.

**Comment by LNJ2** [comment]
There are now two tables in one database. One for caching the roster, so you don't have to wait for your contacts on startup (working) and one for the messages (not working currently).

**Comment by LNJ2** [comment]
It's working everything, now! :)

**Pull request merged**
