### PR TITLE
Redesign login page

### PR DESCRIPTION
**Pull request by SohnyBohny**
More responsive design for login page.
Rearranging the gui elements among each other.

---

image

### CODE REVIEW

**Comment by JBBgameich** [comment]
If I'm not mistaken you could use a ColumnLayout instead of a one-column GridLayout.
I don't really like the connect button filling the whole width, @LNJ2 and @ilyaishere what do you think?

Thanks for submitting a pull request and for your interest in Kaidan :)

**Comment by IlyaBizyaev** [comment]
I also don't really fancy control elements filling all width, although that's what we have currently. We'll probably need to constraint their width to make some centered login form. Anyway, I'm afraid I don't see this change as a way forward...

**Comment by LNJ2** [comment]
I think that this would actually improve the UI on mobile phones, but not on tablets and on desktop platforms. If your initial intention was to just fix the size of the button (the text is overlapping sometimes or the padding is too small), there are other ways to do that.

@JBBgameich and I drawed a mock-up for a new log in page while waiting at school. I can send that when I'm home.

But I'm very happy to see a new contributor here! :+1: :smiley:

**Comment by SohnyBohny** [comment]
I've changed color of connect button to fit the color theme and set maximum width for desktop and tablet devices.

image
image

**Comment by JBBgameich** [comment]
That looks much better! I will do a more complete review when I'm at home.

**Comment by SohnyBohny** [comment]
Okay. I've changed the color similar to the `main.qml/StatusBar`. I'm not sure if this solves your concerns...

Using `highlighted: true` didn't work for me - maybe I had just inserted it into the wrong place

**Comment by IlyaBizyaev** [comment]
That is a Button property you would want to use instead of manually setting the background item:
https://doc.qt.io/qt-5.10/qml-qtquick-controls2-button.html#highlighted-prop
Refer to the docs when in doubt :)

**Comment by JBBgameich** [comment]
I'm not sure if that's the correct way to do that, but Kirigami uses Kirigami.Theme.highlightedTextColor for the Header.

**Comment by SohnyBohny** [comment]
Ready - Thanks - it's definitely better now. In the beginning I wasn't  satisfied with myself either (but didn't know a better way)

**Comment by SohnyBohny** [comment]
I'm not sure with the `Layout.maximumWidth: 450` [here](https://github.com/KaidanIM/Kaidan/pull/249/files#diff-ba2991eebf5b2490bc97b582fcc816efR56)
Maybe someone can check this number on smaller devices or know a better way to handle this

**Pull request merged**
